dist: trusty

sudo: required

git:
  depth: 5

cache:
  ccache: true
  directories:
    - $HOME/.sonar/cache

env:
  matrix:
    - DEFINES="" SONARQUBE="TRUE"
    - DEFINES="CPPFLAGS=-DTGRUB_HP_WORKAROUND" SONARQUBE="FALSE"
    - DEFINES="CPPFLAGS=-DTGRUB_DEBUG" SONARQUBE="FALSE"
  global:
    - secure: "fsJ8kz9HO/dorxiZDKX3sUJZkQXECKlsZJ6GtoGwJWQyDfZ988msG0alZucRyOHr/3dO4I0UENxIWx4FuKIw1t33ngw2Ugi7muKe53KJJa5iUz0dl8uZ4ndSW45cmF9vvCDAaTRsRITRj4SP275CBO7vs83UhB5yiBwaZAhNwzk="
    - secure: "De+Kuku2ICL773X3NKrFzrVBKasPMU9jBEBcpoSDK1AZ8ZsNytiYTOghm0j2jYKE13oPNjXR9wn1FWwF0jhWGwoAr/NvN0/BgHOG83gXmAEVlzU0SrUm7W/elQzbdsnmQfQss7P9GY4EJjARG/aXYw70dDpzNsc/25uS2Iy2M5U="
compiler: gcc
language: c

before_script:
  - jdk_switcher use oraclejdk8
  - java -version
  # fixme
  - chmod a+x runSonarQubeAnalysis.sh

script:
  - echo ${DEFINES}
  - ./autogen.sh && ./configure --target=i386 -with-platform=pc && make ${DEFINES} -j 2 --silent && ./runSonarQubeAnalysis.sh

os:
  - linux

notifications:
  email:
    recipients:
      - daniel@neus-online.eu
addons:
  apt:
    packages:
      - oracle-java8-installer
  sonarqube: true
  coverity_scan:
    project:
      name: Rohde-Schwarz-Cybersecurity/TrustedGRUB2
      description: Build submitted via Travis CI
    notification_email: daniel@neus-online.eu
    build_command_prepend: "./autogen.sh;./configure --target=i386 -with-platform=pc;make clean"
    build_command: make -j 2 --silent
    branch_pattern: coverity_scan
